// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrIzFU549eW3rdOPQmNrZ9Pya8CJKxpks',
    appId: '1:672526374321:web:8ec9698c1f6992c6ae1990',
    messagingSenderId: '672526374321',
    projectId: 'rpg-life-project-87497',
    authDomain: 'rpg-life-project-87497.firebaseapp.com',
    storageBucket: 'rpg-life-project-87497.firebasestorage.app',
    measurementId: 'G-B9ES87ZNJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlLIut45nnJHZ0_8RwJqzdm7Iu-4as2c8',
    appId: '1:672526374321:android:3195a2ba7c426c0fae1990',
    messagingSenderId: '672526374321',
    projectId: 'rpg-life-project-87497',
    storageBucket: 'rpg-life-project-87497.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrIzFU549eW3rdOPQmNrZ9Pya8CJKxpks',
    appId: '1:672526374321:web:1a07083e8ef11709ae1990',
    messagingSenderId: '672526374321',
    projectId: 'rpg-life-project-87497',
    authDomain: 'rpg-life-project-87497.firebaseapp.com',
    storageBucket: 'rpg-life-project-87497.firebasestorage.app',
    measurementId: 'G-H4FSHV2P4S',
  );
}
